# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu.xdc

# IP: ip/Memory/Memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Memory || ORIG_REF_NAME==Memory} -quiet] -quiet

# IP: ip/Control_Memory/Control_Memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Control_Memory || ORIG_REF_NAME==Control_Memory} -quiet] -quiet
